#Imprima sus iniciales en mayúsculas de imprenta, de manera que apunten hacia la parte inferior de la páginas (acostadas). Construya cada mayúscula de imprenta con la letra que ésta representa

print( "NNNNNNNNNN " )
print( "        N  " )
print( "      N    " )
print( "    N      " )
print( "  N        " )
print( "NNNNNNNNNN " )
print( "\n" )
print( "MMMMMMMMMM " )
print( "        M  " )
print( "      M    " )
print( "    M      " )
print( "      M    " )
print( "        M  " )
print( "MMMMMMMMMM " )
print( "\n" ) 
print( "MMMMMMMMMM " )
print( "        M  " )
print( "      M    " )
print( "    M      " )
print( "      M    " )
print( "        M  " )
print( "MMMMMMMMMM " )